# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gj2Rt6ZNsvShdAC-MFLpBsWXevUXpKNU
"""

print("Q1. Average of three numbers entered by user")
a=int(input("Enter first number "))
b=int(input("Enter second number "))
c=int(input("Enter third number "))
d=round((a+b+c)/3,2) 
print("The average of given three numbers rounded off to two decimal places is-",d)

print(" ")
print("Q2. Program to compute an individual's gross income")
print("10000$ Standard Deduction for every individual")
print("Extra 3000$ Deduction for each dependent on the indiavidual")
print("Uniform 20% Tax rates apply to the taxable income of everybody")
net_income=int(input("Income of the individual "))
number_of_dependents=int(input("Number of dependents "))
taxable_income=net_income-10000-3000*number_of_dependents
tax=taxable_income*20/100
gross_income=net_income-tax
print("The gross income after deduction and considering number of dependents is-",gross_income)
print("The amount of tax to be paid is 'Income-Gross Income' which is",tax)

print(" ")
print("Q3. Finding exact number of minutes and seconds in input seconds")
given_seconds=int(input("Enter number of seconds "))
minutes=given_seconds//60
seconds=given_seconds%60
print("Minutes in input seconds-",minutes)
print("Seconds in input seconds-",seconds)

print(" ")
print("Q4. Adding 25,25.0 and '25' to produce 75 as a string result")
a=25
b=25.0
c='25'
print("a=25")
print("b=25.0")
print("c='25'")
print("Using code (str(a+b+int(C))) we get the ans-")
sum=a+b+int(c)
print(str(sum))
print("Now we check if this is a string by using the funtion-type(75.0),and we get the type-")
print(type(str(sum)))

print(" ")
print("Q5. Sine and Cosine of any given angle")
from math import sin,cos,pi
deg=0
y=0
x=0
for deg in range(0,346,15):
 rad=deg*(pi/180)
 y=round(sin(rad),4)
 z=round(cos(rad),4)
 print("sin",deg,"=",y,"and cos",deg,"=",z)
